building_types: [SmallOffice, RetailStripmall]
system_types: [HP RTU, MSHP DOAS, PSZ-AC with electric coil, PSZ-AC with gas coil, PSZ-HP, VRF DOAS]
climate_zones: [1A, 2A, 2B, 3A, 3B, 3C, 4A, 4B, 4C, 5A, 5B, 5C, 6A, 6B, 7A, 8A]